spring:
  application:
    name: bank_rest
  datasource:
    url: jdbc:postgresql://postgres:5432/bank
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/19-01-changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
app:
  user:
    exception-message:
      not-found-by:
        Id: "User with this ID was not found"
        Username: "User with this username was not found"
      already-exists-by:
        email: "User with this email already exists"
        username: "User with this username already exists"
  card:
    pan-for-number: "fjk93jf9w84jf9w4jf9834jf9wjf3"
    exception-message:
      already-exists-by:
        Id: "Card with this ID already exists"
        number: "Card with this number already exists"
      not-found-by:
        Id: "Card with this ID was not found"
        number: "Card with this number was not found"
      wrong-owner-exception: "The card owner doesn’t match the user’s card owner."
      equal-id: "These cards are the same"
      not-enough-balance: "Insufficient funds"
      card-expiry: "Invalid card expiry date"
      card-status: "Invalid card status"
  ticket:
    already-exists-by:
      cardId: "Ticket with this card ID already exists"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  card-encryption-key: 12345678901234567890123456789012